### PR TITLE
 Problem: does not build with nix-build-travis-fold.sh release.nix

### PR DESCRIPTION
**Pull request by clacke**
Solution: Bring in updated scripts, update racket2nix to make fvm build.

Also make use of hydra.

### CODE REVIEW

**Comment by clacke** [comment]
Hydra is ready to consume release.nix.

**Comment by sjmackenzie** [comment]
ein't happenin'

**Comment by clacke** [comment]
Huh. Did I bump to the wrong racket2nix? That message is from pre-142.

**Comment by sjmackenzie** [comment]
Yeah I think so!

**Comment by clacke** [comment]
Oh yeah, and good catch on the URL. I guess it's not optimal that the script only work on my machine. :-)

**Comment by clacke** [comment]
- Spock, what's this?
 - Green, sir.

**Comment by sjmackenzie** [comment]
Actually I should have just merged it and created a new PR. Probably best not sticking commits on other people's PRs. Anyway, let's see what hydra says!

**Comment by clacke** [comment]
\# | Date | Input changes | Success
-- | -- | -- | --
30 | 26m ago | cardano-wallet →     faad47b, nixpkgs →     c29d2fd | 2

**Pull request merged**
